spring.config.import=optional:file:.env[.properties]

spring.profiles.active=${SPRING_PROFILE:dev}

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.ai.openai.api-key=${OPENAI_API_KEY}